---
# Fase 1: Maak AD user 
- name: Maak Active Directory gebruiker (1)
  hosts: dc
  gather_facts: no
  vars_prompt:
    - name: "first_name"
      prompt: "Voer de voornaam van de nieuwe gebruiker in"
      private: no
    - name: "last_name"
      prompt: "Voer de achternaam van de nieuwe gebruiker in"
      private: no
    - name: "department"
      prompt: "Voer de afdeling van de nieuwe gebruiker in"
      private: no
    - name: "salary_number"
      prompt: "Voer het salarisnummer van de nieuwe gebruiker in"
      private: no

  vars_files:
    - vault.yml
    - vars.yml

  roles:
    - createuser

# Fase 2: Deploy 1 virtuele machine in netlab
- name: Rol virtuele machine uit (2)
  hosts: localhost
  become: true
  gather_facts: no
  collections:
    - community.vmware
  vars_files:
    - vault.yml
    - vars.yml
    - vmname.yml

  tasks:
    - name: Rol virtuele machine uit (2.1)
      include_role:
        name: deployvm
      vars:
        vm_template: "Templ_Windows10a"
        vm_network: "2732_I530600_PVlanA"
      tags: deployvm

    # Wacht tot de vm is gestart
    - name: Wacht tot machine beschikbaar is (2.2)
      wait_for:
        host: "{{ vm_ip }}"
        port: 5985
        delay: 60         
        timeout: 300
        sleep: 10
        state: started
      delegate_to: localhost

# Fase 3: Voeg de VM toe aan het domein
- name: Voeg machine toe aan domein (3.1)
  hosts: deployed_vms
  gather_facts: no
  vars_files:
    - vault.yml
    - vars.yml
    - vmname.yml
  tasks:
    - include_role:
        name: domainadd
      vars:
        vm_name: "{{ var_vm_name }}"
      tags: domainadd

# Fase 4: Verwijder `vmname.yml`
- name: Verwijder variabelen (4)
  hosts: localhost
  become: true
  tasks:
    - name: Verwijder variabelen (4.1)
      set_fact:
        var_vm_name: ""
        vm_ip: ""
      delegate_to: localhost
