---
- name: Maak nieuwe gebruiker
  win_shell: net user "{{ first_name | lower }}.{{ last_name | replace(' ', '') | lower }}" "{{ default_password }}" /add /logonpasswordchg:yes
  register: user_creation

- name: Maak loginnaam gebruiker (UPN)
  win_shell: |
    $username = "{{ first_name | lower }}.{{ last_name | replace(' ', '') | lower }}"
    $upn = "$username@{{ domain }}"
    Set-ADUser -Identity $username -UserPrincipalName $upn -ChangePasswordAtLogon $true
  when: user_creation.rc == 0

- name: Voeg gebruiker toe aan afdeling groep
  win_shell: net localgroup "{{ department }}" "{{ first_name | lower }}.{{ last_name | replace(' ', '') | lower }}" /add
  when: user_creation.rc == 0

- name: Stel vm naam (var_vm_name) in 
  set_fact:
    var_vm_name: "WRS-{{ first_name | lower }}{{ last_name | replace(' ', '') | lower }}-{{ salary_number }}"

- name: Schrijf vm naam naar bestand
  copy:
    content: "var_vm_name: {{ var_vm_name }}\n"
    dest: "vmname.yml"
    mode: '0644'
  delegate_to: localhost
