---
- name: Virtuele machine toevoegen aan domein
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    hostname: "{{ vm_name }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_join_result

- name: Check of virtuele machine opnieuw moet worden gestart
  win_reboot:
    reboot_timeout: 600
  when: domain_join_result.reboot_required | default(false)

- name: Virtuele machine is aan het domein toegevoegd
  debug:
    msg: "The VM is added to the domain"
