- name: Maak Virtuele machine aan
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    datastore: "{{ vcenter_datastore }}"
    folder: "{{ vm_folder }}"
    template: "{{ vm_template }}"
    name: "{{ var_vm_name }}"
    resource_pool: "{{ recourse_pool }}"
    cluster: "{{ netlabcluster }}"
    state: powered-on
    hardware:
      memory_mb: 4096
      num_cpus: 2
    networks:
      - name: "{{ vm_network }}"
    wait_for_ip_address: yes
  delegate_to: localhost

- name: Haal IP adres van machine op
  community.vmware.vmware_guest_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ var_vm_name }}"
  delegate_to: localhost
  register: vm_info

- name: Haal IP adres op
  set_fact:
    vm_ip: "{{ vm_info.instance.ipv4 }}"
  when: vm_info.instance.ipv4 is defined

- name: Schijf IP adres naar bestand
  lineinfile:
    path: "vmname.yml"
    line: "vm_ip: {{ vm_ip }}"
  when: vm_ip is defined
  delegate_to: localhost

- name: Schijf machine gegevens naar inventory
  add_host:
    name: "{{ var_vm_name }}"
    ansible_host: "{{ vm_ip }}"
    ansible_user: student
    ansible_password: student
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    groups: deployed_vms
  when: vm_ip is defined

