---
- name: Webpagina uitrollen 
  hosts: webservers
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Upgrade alle packages
      apt:
        upgrade: dist

    - name: Zorg ervoor dat Apache draait
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Kopieer de HTML-pagina naar de webserver
      ansible.builtin.copy:
        src: ~/ansible/files/index.html
        dest: /var/www/html/index.html 

    - name: Configureer rechten op servers
      ansible.builtin.file:
        path: /var/www/html/index.html
        owner: www-data  
        group: www-data 
        mode: '0644'
